remote_theme: pages-themes/hacker

title: "vlpatton.gay"
description: "vaguely programming related stuff"

plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      author: Harper Londyn
      layout: default
