remote_theme: b2a3e8/jekyll-theme-console

title: "vlpatton.gay"
description: "vaguely programming related stuff"

header_pages:
  - index.md
  - about.md
  - posts/index.md

style: dark

plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      author: Harper Londyn
      layout: default
