remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
defualts:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      author: 'Harper Londyn'
      layout: 'default'
